# Lightweight Nginx Alpine image use kar rahe hain static site serve karne ke liye
FROM nginx:alpine

# Default Nginx static folder me index.html copy kar rahe hain
COPY index.html /usr/share/nginx/html/index.html

# Port 80 expose kar rahe hain
EXPOSE 80