# Nginx Alpine image use kar rahe hain
FROM nginx:alpine

# Default Nginx config ko hatakar hamara custom reverse proxy config overwrite kar rahe hain
COPY nginx.conf /etc/nginx/nginx.conf

# Proxy Port 80 expose kar rahe hain
EXPOSE 80