events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Internal microservices Routing
    upstream backend_service {
        server backend:5000;
    }

    upstream frontend_service {
        server frontend:80;
    }

    server {
        listen 80;
        server_name localhost;

        # Route 1: Direct traffic to Frontend Interface
        location / {
            proxy_pass http://frontend_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route 2: Route API calls transparently to Microservice Backend
        location /api/ {
            proxy_pass http://backend_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}